Домашнее задание 7
NadyaBelozerova/homeworks pull request #1
Opened 2020-09-26 10:12 UTC by NadyaBelozerova

2020-09-27 08:14 UTC, ios-review requested changes
За гит 🔥

Задание требует некоторых доработок.

2020-09-27 08:14 UTC, ios-review commented on hw7/SecondViewController.swift
> +   }
От данного контроллера не должно быть переходов.
Segue - это модель перехода, которая описывает открытие вью контроллера назначения (destination) из исходного вью контроллера (source).

Согласно заданию в данном контроллере должно быть три кнопки, по нажатию на любую из которых экран должен закрываться.
Закрытие означает, что данный экран будет убран и показан предыдущий, на котором должен быть лейбл и кнопка Изменить, то есть FirstViewController.
Закрыть экран можно с помощью функции https://developer.apple.com/documentation/uikit/uiviewcontroller/1621505-dismiss
Для реакции на нажатие необходимо создать @IBAction функцию.

Также при закрытии в FirstViewController должно передаться значение текста, которое показывает какая кнопка была нажата.
Это можно сделать с помощью паттерн Delegate.
Он был рассмотрен в видео-лекции.
Предлагаю еще раз посмотреть лекцию.
Если будут вопросы, то буду рад помочь.

2020-09-27 08:14 UTC, ios-review commented on hw7/FirstViewController.swift
> +class FirstViewController: UIViewController {
<img width="1679" alt="Screenshot 2020-09-27 at 15 01 56" src="https://user-images.githubusercontent.com/62285448/94359829-74a4f800-00d3-11eb-9769-7c22fcbf2ff7.png">

2020-09-27 08:14 UTC, ios-review commented on hw7/ParentViewController.swift
> +class ParentViewController: UIViewController {
<img width="1677" alt="Screenshot 2020-09-27 at 15 02 37" src="https://user-images.githubusercontent.com/62285448/94359844-90a89980-00d3-11eb-99ab-dd6b68c0d0b3.png">

2020-09-27 08:14 UTC, ios-review commented on hw7/ParentViewController.swift
> +            }
segue должен быть только 1.

ChildViewController встраивается в ParentViewController (embed).
В этом методе может происходит дополнительная установка свойств, которую могут помочь в обмене данными в двух контроллерах.
Например, установить delegate.

Передать любые данные во встроенный ViewController можно, также используя метод prepare(for:sender:).
В этом же методе можно сохранить ссылку на дочерний ViewController.

Например, представим есть ContainerViewController и EmbeddedViewController. EmbeddedViewController встраивается в ContainerViewController с помощью ContainerView.
```

 class ContainerViewController: UIViewController {
     var embeddedViewController: EmbeddedViewController?
     
     override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
         if segue.identifier == "ToEmbeddedViewController", let embeddedViewController = segue.destination as? EmbeddedViewController {
             self.embeddedViewController = embeddedViewController
             embeddedViewController.delegate = self
         }
     }
 }

 extension ContainerViewController: EmbeddedViewControllerDelegate {
     
 }

 protocol EmbeddedViewControllerDelegate: AnyObject {
     
 }

 class EmbeddedViewController: UIViewController {
     weak var delegate: EmbeddedViewControllerDelegate?
 }
```

 Теперь у обоих контроллеров есть ссылка друг на друга и они могут передавать данные, используя эти ссылки.
 ContainerViewController может использовать свойство embeddedViewController, а EmbeddedViewController - свойство delegate.

 Очень хорошо шаги описаны в статье в разделе Using Interface Builder по ссылке https://medium.com/@dushyant_db/setting-up-a-container-view-using-interface-builder-and-via-code-7ac1a7f0a0d6

2020-09-29 09:05 UTC, ios-review requested changes
Все задания выполнены в соответствии с условиями👍

Поработаем немного над "красотой" кода?

2020-09-29 09:05 UTC, ios-review commented on hw7/ChildViewController.swift
> +    }
Предлагаю для всего приложения создать модель ColorPallete и использовать ее во всех контроллерах.

```
enum ColorPallete: Int {
    case red = 0
    case green
    // etc

    var rgb: UIColor {
        // return appropriate value
    }

    var selectedDescription: String {
        // return appropriate value
    }

    var name: String {
        // return appropriate value
    }
}
```
У каждой кнопки задать tag, значение которого соответствует нужному кейсу ColorPallete.
У любой вью есть свойство tag, с помощью которого можно идентифицировать эту вью.
https://developer.apple.com/documentation/uikit/uiview/1622493-tag
Задать свойство можно как в коде, так и в сториборде.
Задайте соответствие tag кнопки и raw value для перечисления ColorPallete.
Создавать с помощью rawValue инициализатора
`let color = ColorPallete(rawValue: sender.tag)`

Для любой @IBAction функции можно назначить сколь угодно много кнопок для обработки нажатия.
Количество кода можно уменьшить, если обмениваться с другими контроллерами (через делегат) объектом перечисления ColorPallete.
А внутри контроллеров уже использовать вычислимые свойства этой модели для получения нужного значения: цвета или текста вроде "Выбран зеленый".

Будет примерно так:
```
@IBAction func buttonPressed(_ sender: UIButton) {
    guard let color = ColorPallete(rawValue: sender.tag) else { return }
    delegate?.update(color)
    dismiss(animated: true) 
}
```
Данную @IBAction функцию назначить для всех кнопок на контроллере.

Так сделать для всех контроллеров приложения.

2020-09-29 09:05 UTC, ios-review commented on hw7/ChildViewController.swift
>      }
Пустые методы, много пустых строк и другие "неряшливости" можно поправить)
Будет смотреться и читаться приятнее)

2020-10-01 08:09 UTC, NadyaBelozerova commented on hw7/ViewController.swift
> +   }
Правильно ли я поняла, что нужно сделать один enum ColorPallete в одном из контроллеров и использовать потом его во всех контроллерах?

2020-10-01 08:09 UTC, NadyaBelozerova commented on hw7/SecondViewController.swift
Здесь объединила три @IBAction в один.

2020-10-01 08:09 UTC, NadyaBelozerova commented on hw7/SecondViewController.swift
Насчет того, как менять цвет экрана по нажатию на кнопки  не совсем понимаю. Сделала вот так, но сомневаюсь, что правильно.

2020-10-01 08:09 UTC, NadyaBelozerova commented on hw7/ChildViewController.swift
> +
В ChildViewController.swift  я сделала один @IBAction вместо трех, но как это же сделать в ParentViewController.swift не поняла. И если цель была уменьшить количество кода, то у меня его стало только больше, ужас((

2020-10-01 08:09 UTC, NadyaBelozerova commented on hw7/ParentViewController.swift
>  }
В этом контроллере не получилось сделать никаких важных изменений, кроме удаления лишних строчек.

2020-10-04 11:26 UTC, ios-review commented on hw7/ViewController.swift
> +   }
ColorPallete - по сути отдельный файл.
ColorPallete представляет собой модель данных всего приложения.
Для удобного преобразования нажатой кнопки в модель, которую имеет удобный для нас вид. 
Дальше с помощью конкретного значения этой модели вычисляется UIColor и String для отображения на экране.

Данная модель позволяет нам ограничить все множество цветов только до тех, которые поддерживаются в нашем приложении.
Иметь в одном месте все преобразования этой модели.
Если мы захотим добавить новый цвет, то достаточно изменить только эту модель.
В случае ее отсутствия придется искать все места, где новый цвет может использоваться и менять эти места.

В общем случае всегда рекомендуется создавать модель данных для приложения, чтобы единое место изменения этой модели.
Также компилятор языка позволяет проверять некоторые ошибки. 
Например, использование цвета, который не поддерживается приложением.

2020-10-04 11:26 UTC, ios-review commented on hw7/ViewController.swift
> +   }
Моделирование данных - очень большая тема.
На протяжении всего курса мы часто будем заниматься моделированием.

2020-10-04 11:41 UTC, ios-review requested changes
Осталось пару штришков)
Направление движения задали верное👍

2020-10-04 11:41 UTC, ios-review commented on hw7/ChildViewController.swift
> +        delegate?.changeColor3(color3.rgb)
Кнопкам в сториборде необходимо назначить тот tag, который соответствует необходимому raw value значению перечисления ColorPallete.
Например,
для зеленой tag = 1, такой же как ColorPallete.green
для желтой tag = 4, такой же как ColorPallete.yellow
для пурпурной tag = 5, такой же как ColorPallete.purple

После этого у делегата создать всего один метод.
```
protocol ChildViewControllerDelegate: AnyObject {
    func changeColor(_ color: ColorPallete)
 }
```

Внутри реализации метода нажатия на кнопку:
```
    @IBAction func buttonPressed(_ sender: UIButton) {
          guard let color = ColorPallete(rawValue: sender.tag) else { return } // здесь будет создан нужный ColorPallete, так как tag соответствует raw value требуемого ColorPallete
          delegate?.changeColor(color)
}
```

В реализации метода делегата:
```
extension ParentViewController: ChildViewControllerDelegate {
     func changeColor(_ color: ColorPallete) {
         view.backgroundColor = color.rgb
     }
 }
```

Между контроллерами приложения обмениваемся конкретным значением модели данных приложения, то есть ColorPallete.
А там где необходим цвет или текст, преобразовываем значение модели данных в цвет или текст с помощью доступных свойств.

2020-10-04 11:41 UTC, ios-review commented on hw7/ParentViewController.swift
> +    }
Три функции объединить в одну.
По нажатию создавать ColorPallete с помощью tag кнопки.
Преобразовывать созданный ColorPallete в UIColor по нужному свойству.

2020-10-04 11:41 UTC, ios-review commented on hw7/SecondViewController.swift
> +            dismiss(animated: true)
Также:
1. Создание ColorPallete на основе sender.tag
2. Передача этого значения через метод делегата.
3. Закрытие экрана.

2020-10-04 11:41 UTC, ios-review commented on hw7/ViewController.swift
> +        case purple2 = 8
Повторяющиеся значения.
green, green2, green3 по сути ничем не отличаются.
На нужных контроллерах можно устанавливать тот tag, который соответствует raw value требуемого ColorPallete для этой кнопки.

2020-10-04 11:41 UTC, ios-review commented on hw7/ViewController.swift
> +}
Пустой класс не нужен.
Можно его удалить.

2020-10-04 11:41 UTC, ios-review commented on hw7/ViewController.swift
> +enum ColorPallete: Int {
Модель можно вынести в отдельный файл и назвать его ColorPallete.

2020-10-04 11:41 UTC, ios-review commented on hw7/SecondViewController.swift
> +    func screenColorBlue(_ rgb: UIColor)
Можно создать один метод, а в его реализации изменять текст лейбла и цвет фона.

`func changeColor(_ color: ColorPallete)`

2020-10-05 14:02 UTC, ios-review approved these changes
🔥🔥🔥

Реквест мержим

2020-10-05 14:02 UTC, ios-review commented on hw7/ColorPallete.swift
> +            return ""
Пустые строки лучше не оставлять, так как. в дальнейшем может понадобиться и для желтого с пурпурным данный текст.

2020-10-05 14:02 UTC, ios-review commented on hw7/FirstViewController.swift
> +    }
Две функции можно было объединить в одну:
```
    func changeColor(_ color1: ColorPallete) {
          firstLabelVC.text = "\(color1.selectedDescription)"  
          view.backgroundColor = color1.rgb
      }
```

Пробуйте всегда писать меньше)
Чем меньше, тем лучше и проще)

2020-10-05 14:02 UTC, ios-review commented on hw7/SecondViewController.swift
> +   }
И после реализации изменения фона и текста лейбла в одной функции здесь код тоже уменьшится так:
```
    @IBAction func buttonPressed(_ sender: UIButton) {
          guard let color1 = ColorPallete(rawValue: sender.tag) else { return }
          delegate?.changeColor(color1)
          dismiss(animated: true)
     }
```

2020-10-18 10:30 UTC, closed without merging